apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  postgres-username: BASE64_ENCODED_USERNAME
  postgres-password: BASE64_ENCODED_PASSWORD


#echo -n "your-postgres-username" | base64
#echo -n "your-postgres-password" | base64
